### ISSUE TITLE
Debug@2.2.0 has known vulnerabilities. Please upgrade.

### ISSUE THREAD

**Issue by dcvice1967** [SangHakLee/swagger-express-jsdoc#1]
The version of debug used has know issues. Can you upgrade it to use a version greater than 3.0.1.

**Comment by Quizart** [comment]
install also reports that ejs has critical security bugs fixed in 2.5.5, please upgrade that as well

**Comment by SangHakLee** [comment]
@dcvice1967, @Quizart 

Hi, Developers.

I've finished working on your request.

I'm sorry to be late.

We have also updated other vulnerabilities, including `debug`, so please check back for additional issues.

Thanks for joining my project.

[swagger-express-jsdoc@1.0.4](https://www.npmjs.com/package/swagger-express-jsdoc/v/1.0.4)
