### ISSUE TITLE
Update swagger-ui-express version

### ISSUE THREAD

**Issue by omerl13** [SangHakLee/swagger-express-jsdoc#2]
Please update swagger-ui-express from `^1.0.7` to `^4.0.2`, to keep the UI up to date.

**Comment by SangHakLee** [comment]
@omerl13 

Hi, I've checked your issue now and modified it to your requirements.

I updated to the latest version, [4.0.4](https://www.npmjs.com/package/swagger-ui-express/v/4.0.4), today.

I have updated the other modules to the latest version.

Thanks for participating in my project, and leave another issue next time.
I'll fix it fast next time.
